//  Created by Geoff Pado on 10/9/24.
//  Copyright © 2024 Cocoatype, LLC. All rights reserved.

struct Code128ElementToStringConverterModeB {
    func string(for element: Code128Element) throws -> String {
        switch element {
        case .e00: " "
        case .e01: "!"
        case .e02: "\""
        case .e03: "#"
        case .e04: "$"
        case .e05: "%"
        case .e06: "&"
        case .e07: "'"
        case .e08: "("
        case .e09: ")"
        case .e0a: "*"
        case .e0b: "+"
        case .e0c: ","
        case .e0d: "-"
        case .e0e: "."
        case .e0f: "/"
        case .e10: "0"
        case .e11: "1"
        case .e12: "2"
        case .e13: "3"
        case .e14: "4"
        case .e15: "5"
        case .e16: "6"
        case .e17: "7"
        case .e18: "8"
        case .e19: "9"
        case .e1a: ":"
        case .e1b: ";"
        case .e1c: "<"
        case .e1d: "="
        case .e1e: ">"
        case .e1f: "?"
        case .e20: "@"
        case .e21: "A"
        case .e22: "B"
        case .e23: "C"
        case .e24: "D"
        case .e25: "E"
        case .e26: "F"
        case .e27: "G"
        case .e28: "H"
        case .e29: "I"
        case .e2a: "J"
        case .e2b: "K"
        case .e2c: "L"
        case .e2d: "M"
        case .e2e: "N"
        case .e2f: "O"
        case .e30: "P"
        case .e31: "Q"
        case .e32: "R"
        case .e33: "S"
        case .e34: "T"
        case .e35: "U"
        case .e36: "V"
        case .e37: "W"
        case .e38: "X"
        case .e39: "Y"
        case .e3a: "Z"
        case .e3b: "["
        case .e3c: "\\"
        case .e3d: "]"
        case .e3e: "^"
        case .e3f: "_"
        case .e40: "`"
        case .e41: "a"
        case .e42: "b"
        case .e43: "c"
        case .e44: "d"
        case .e45: "e"
        case .e46: "f"
        case .e47: "g"
        case .e48: "h"
        case .e49: "i"
        case .e4a: "j"
        case .e4b: "k"
        case .e4c: "l"
        case .e4d: "m"
        case .e4e: "n"
        case .e4f: "o"
        case .e50: "p"
        case .e51: "q"
        case .e52: "r"
        case .e53: "s"
        case .e54: "t"
        case .e55: "u"
        case .e56: "v"
        case .e57: "w"
        case .e58: "x"
        case .e59: "y"
        case .e5a: "z"
        case .e5b: "{"
        case .e5c: "|"
        case .e5d: "}"
        case .e5e: "~"
        case .e5f: "\u{7f}"
        case .e60, .e61, .e62, .e63, .e64, .e65, .e66, .e67, .e68, .e69, .e6a:
            throw Code128ConversionError.noEquivalentCharacter(element)
        }
    }
}
